# Generated by Django 2.2.3 on 2019-07-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipio',
            name='region',
        ),
        migrations.AddField(
            model_name='municipio',
            name='regiones',
            field=models.ManyToManyField(to='municipio.Region'),
        ),
    ]
